local Server = {}
Server.wrappedPeripheral = nil
Server.listenPort = nil
Server.clients = nil

function Server:init(wrappedPeripheral, listenPort)
    self.wrappedPeripheral = wrappedPeripheral
    self.listenPort = listenPort
    if not wrappedPeripheral.isOpen(listenPort) then
        wrappedPeripheral.open(listenPort)
    end
    self.clients = {}
end

-- function uuid() - Generated by LLM
local function uuid()

    local template = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'

    return string.gsub(template, '[xy]', function(c)
        local v

        if c == 'x' then
            v = math.random(0, 15)
        else
            v = math.random(8, 11)
        end

        return string.format('%x', v)
    end)
end

function Server:initClient(id, replyPort)
    client = {}
    self.clients[id] = client
    client.peripherals = {}
    client.packets = {} -- Structure: ["id": "some uuid", "requestTime": xxx, "timeout": yyy, "onResult": callbackFunction]
    client.replyPort = replyPort
    return client
end

-- Server:sendRequest
-- id: target CC device to send the request to
-- code: the code the CC device should evaluate
-- parameters: parameters for the code. E.g. {x = 10, y = 20}
-- callbackFunction: the function that will be called once an answer is received
-- timeout: after how many ticks to remove the request from the queue.
-- timeoutCallbackFunction: function to call when the request times out
function Server:sendRequest(id, code, parameters, callbackFunction, timeout, timeoutCallbackFunction)
    if timeout == nil then
        timeout = 200
    end
    client = self.clients[id]
    if client == nil then
        return nil
    end
    requestId = uuid()
    requestTime = os.time()
    request = textutils.serializeJSON({
        id = id,
        requestId = requestId,
        requestType = "request",
        code = code,
        parameters = parameters
    })
    self.wrappedPeripheral.transmit(client.replyPort, self.listenPort, request)
    
    packet = {
        id = requestId,
        requestTime = requestTime,
        timeout = timeout,
        onResult = callbackFunction,
        onTimeout = timeoutCallbackFunction
    }

    client.packets[id] = packet

    return packet
end

function Server:handleEvent(event)
    term.setCursorPos(1, 1)
    if event[1] == "modem_message" then
        local event, side, channel, replyChannel, message, distance = event[1], event[2], event[3], event[4], event[5], event[6]
        if channel == self.listenPort then
            -- Packet types: heartbeat, requestResult
            deserializedMessage = message -- textutils.unserializeJSON(message)
            requestType = deserializedMessage.requestType
            if requestType == "heartbeat" then
                -- capabilities packet structure:
                --  {
                --      "id": "computer/turtle identifier",
                --      "requestType": "heartbeat",
                --      "clientType": "Pocket/Turtle/PC",
                --      "isAdvanced": bool -- Whether the client is a regular PC or advanced one
                --      "peripherals": [
                --          "side": {
                --              "keys": {...} -- functions
                --          }
                --      ]
                --  }
                local id = deserializedMessage.id
                local client = self.clients[id]
                if client == nil then
                    client = self:initClient(id, replyChannel)
                end
                client.clientType = deserializedMessage.clientType
                client.isAdvanced = deserializedMessage.isAdvanced
                client.peripherals = deserializedMessage.peripherals
            elseif requestType == "requestResult" then
                -- requestResult packet structure:
                --  {
                --      "id": "computer/turtle identifier",
                --      "requestType": "requestResult",
                --      "requestId": "request identifier", -- set randomly
                --      "success": bool
                --      "result": {result} -- dynamic table
                --  }
                local client = self.clients[id]
                if client ~= nil then -- TODO: handle client == nil case
                    requestId = deserializedMessage.requestId
                    success = deserializedMessage.success
                    result = deserializedMessage.result
                    request = client.packets[requestId]
                    if request ~= nil then
                        request.result = result
                        if request.onResult ~= nil then
                            request.onResult(request)
                        end
                        client.packets[requestId] = nil
                    end
                end
            end
        end
    end
    -- TODO implement timeout (and use onTimeout() too.)
end


return Server