local Client = {}
Client.isAdvanced = term.isColor()
Client.isPocket = pocket ~= nil
Client.isTurtle = turtle ~= nil
Client.isPC = pocket == nil and turtle == nil
Client.clientType = nil
Client.serverId = nil
Client.serverPort = nil
Client.responsePort = nil
Client.id = nil
local sides = {"left", "right", "front", "back", "up", "down"}

function Client:init(wrappedPeripheral, serverId, serverPort, responsePort)
    self.wrappedPeripheral = wrappedPeripheral
    self.serverId = serverId
    self.serverPort = serverPort
    self.responsePort = responsePort
    if not wrappedPeripheral.isOpen(responsePort) then
        wrappedPeripheral.open(responsePort)
    end
    local label = os.getComputerLabel()
    if label == nil or label == "" then
        self.id = os.getComputerID()
    else
        self.id = label
    end
    if self.isPC then
        self.clientType = "PC"
    elseif self.isTurtle then
        self.clientType = "Turtle"
    elseif self.isPocket then
        self.clientType = "Pocket"
    end
end

-- function Client:execCode: generated by LLM
function Client:execCode(code, params)
    local env = setmetatable({}, { __index = _ENV })

    if params then
        for k, v in pairs(params) do
            env[k] = v
        end
    end

    local compiledCode, compileError = load(code, "dynamic_code", "t", env)

    if not compiledCode then
        return false, compileError
    end

    local ok, result = pcall(compiledCode)

    if not ok then
        return false, result
    end

    return true, result
end

function Client:heartbeat()
    peripherals = {}
    for _, side in ipairs(sides) do
        local sidePeripheral = peripheral.wrap(side)
        local keys = {}
        if sidePeripheral ~= nil then
            for key, _ in pairs(sidePeripheral) do
                table.insert(keys, key)
            end
            peripherals[side] = keys
        end
    end

    request = {
        id = self.id,
        requestType = "heartbeat",
        clientType = self.clientType,
        isAdvanced = self.isAdvanced,
        peripherals = peripherals
    }
    self.wrappedPeripheral.transmit(self.serverPort, self.responsePort, request)
end

function Client:handleEvent(event)
    if event[1] == "modem_message" then
        local event, side, channel, replyChannel, message, distance = event[1], event[2], event[3], event[4], event[5], event[6]
        if channel == self.responsePort then
            -- Packet types: request
            local deserializedMessage = textutils.unserializeJSON(message)
            local id = deserializedMessage.id
            if id ~= self.id then
                return
            end
            local requestType = deserializedMessage.requestType
            if requestType == "request" then
                local requestId = deserializedMessage.requestId
                local code = deserializedMessage.code
                local parameters = deserializedMessage.parameters
                local ok, result = self:execCode(code, parameters)
                response = {
                    id = self.id,
                    requestType = "requestResult",
                    requestId = requestId,
                    success = ok,
                    result = result
                }
                self.wrappedPeripheral.transmit(replyChannel, self.responsePort, textutils.serializeJSON(response))
            end
        end
    end
end

return Client